# Docker compose cho Azure VM
services:
  coturn:
    image: coturn/coturn:latest
    container_name: my-coturn
    restart: always
    network_mode: "host"
    command:
      - -n
      - --log-file=stdout
      - --listening-port=3478
      - --min-port=49152
      - --max-port=65535
      - --user=b4330d3ea3c3942b88622212:ukF6RZmyRwcWjywa
      - --realm=20.2.88.224
      - --external-ip=20.2.88.224/10.0.0.4
      - --verbose
